# Seek to recreate the genome_assembly from the cellarium lab
data_path: fine_tune/datasets/genome
organism: human
gencode_version: 45 
ensembl_version: null # corresponds to ensembl 111
host: null
attrs:
- ensembl_gene_id
- gene_biotype
- external_gene_name
- external_gene_source
- external_synonym
filters: null
rename_columns:
  ensembl_gene_id: ensembl_id
  gene_biotype: biotype
  external_gene_name: symbol
  external_gene_source: source
  external_synonym: synonym
debug: 0
use_cache: false
