# lightning.pytorch==2.2.1
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: 
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  # - class_path: lightning.pytorch.callbacks.EarlyStopping
  #   init_args:
  #     monitor: train_loss
  #     min_delta: 0.0
  #     patience: 45
  #     mode: min
  fast_dev_run: false
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: false
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
#  transforms:
#   - !CheckpointLoader #do not remove the - , otherwise it messes everything up
#      file_path: ../notebooks/lightning_logs/version_7/checkpoints/epoch=49-step=3150.ckpt
#      attr: model
#      #attr: model._modules.z_encoder.mean_encoder.bias #here we extract the parameter we are looking for model._modules["z_encoder"].mean_encoder.bias
#      convert_fn: cellarium.ml.transforms.load.to_device
  model:
    class_path: cellarium.ml.models.SingleCellVariationalInference
    init_args:
      var_names_g: null
      n_batch: null
      batch_bias_sampled: false
      loaded_bias:
        - !CheckpointLoader #do not remove the - , otherwise it messes everything up
          file_path: ../notebooks/lightning_logs/version_7/checkpoints/epoch=49-step=3150.ckpt
          attr: model
          #attr: model._modules.z_encoder.mean_encoder.bias #here we extract the parameter we are looking for model._modules["z_encoder"].mean_encoder.bias
          convert_fn: cellarium.ml.transforms.load.to_device
      encoder: 
        layers:
        - class_path: cellarium.ml.models.common.nn.LinearWithBatch
          init_args:
            out_features: 128
        output_bias: true
      decoder:
        layers:
        - class_path: cellarium.ml.models.common.nn.LinearWithBatch
          init_args:
            out_features: 128
        output_bias: true
      n_latent: 16
      n_continuous_cov: 0
      n_cats_per_cov: null
      dropout_rate: 0.1
      dispersion: gene
      log_variational: true
      gene_likelihood: nb
      latent_distribution: normal
      encode_covariates: false
      batch_representation: one-hot
      use_batch_norm: both
      use_layer_norm: none
      use_size_factor_key: false
      use_observed_lib_size: true
      library_log_means: null
      library_log_vars: null
      # var_activation: null
      # extra_encoder_kwargs: null
      # extra_decoder_kwargs: null
      batch_embedding_kwargs: null
  optim_fn: torch.optim.Adam
  optim_kwargs: 
    lr: 1e-3
  scheduler_fn: null
  scheduler_kwargs: null
  is_initialized: False
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      #filenames: gs://yx-data/pbmc_count.h5ad
      #filenames: https://storage.googleapis.com/dsp-cellarium-cas-public/test-data/test_0.h5ad
      #filenames: /opt/project/pbmc_count.h5ad #use with cli.py
      filenames: ../data/pbmc_count.h5ad
      #filenames: /home/lys/Dropbox/PostDoc_Glycomics/pbmc_count.h5ad
      limits: [31774]
      shard_size: 31774
      last_shard_size: null
      max_cache_size: 1
      cache_size_strictly_enforced: true
      label: null
      keys: null
      index_unique: null
      convert: null
      indices_strict: true
      obs_columns_to_validate: null
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.densify
    var_names_g:
      attr: var_names
    batch_index_n:
      attr: obs
      key: batch
      convert_fn: cellarium.ml.utilities.data.categories_to_codes
  batch_size: 512
  shuffle: true
  seed: 0
  drop_last: false
  test_mode: false
  num_workers: 0 #changed from 4 to 0 to avoid emmory complaints
ckpt_path: null
