# lightning.pytorch==2.1.3
seed_everything: true
trainer:
  accelerator: gpu
  devices: 1
  log_every_n_steps: 1
  strategy: auto
  max_epochs: 5
  default_root_dir: smoke_test/cellarium_gpt
model:
  model:
    class_path: cellarium.ml.models.CellariumGPT
    init_args:
      d_model: 256
      d_ffn: 512
      n_heads: 8
      n_blocks: 4
      dropout_p: 0.0
      use_bias: false
      max_prefix_len: 2000
      suffix_len: 500
      context_len: null
      attn_mult: 6.0
      input_mult: 1.0
      output_mult: 1.0
      max_value: 1000
      initializer_range: 0.02
      attn_backend: mem_efficient
  optim_fn: torch.optim.AdamW
  optim_kwargs:
    lr: 0.001
    betas:
      - 0.9
      - 0.95
    weight_decay: 0.1
data:
  dadc:
    filenames: https://storage.googleapis.com/dsp-cellarium-cas-public/curriculum/extract_files/extract_{0..9}.h5ad
    limits: null
    shard_size: 10_000
    last_shard_size: null
    max_cache_size: 2
    cache_size_strictly_enforced: true
    label: null
    keys: null
    index_unique: null
    indices_strict: true
    obs_columns_to_validate:
      - total_mrna_umis
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.densify
    var_names_g:
      attr: var_names
    total_mrna_umis_n:
      attr: obs
      key: total_mrna_umis
    obs_names_n:
      attr: obs_names
  batch_size: 5
  shuffle: true
  seed: 0
  drop_last: false
  val_size: 0
  test_mode: false
  num_workers: 1
ckpt_path: null